title: WalrusRPG
description: A tech/magic modpack with a lot of exploration options, featuring Tale of Kingdoms.
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
